Add crud task
MikhailSumarokov95/Task_Tracker pull request #1
Opened 2023-09-24 11:35 UTC by MikhailSumarokov95

2023-09-27 07:11 UTC, zor07 requested changes

2023-09-27 07:11 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/repository/TaskGroupRepository.java
> +    public List<TaskGroup> findAllByOrderByIdAsc();
Проверь плз, будет ли работать если назвать метод findAllOrderById

2023-09-27 07:11 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/repository/TaskRepository.java
> +    public List<Task> findAllByOrderByIdAsc();
findAllOrderById

2023-09-27 07:11 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/repository/TaskRepository.java
> +    public List<Task> findAllByOrderByIdAsc();
Проверь плз будет ли работать с таким неймингом

2023-09-27 07:11 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/entity/TaskGroup.java
> +    private long id;
Long

2023-09-27 07:11 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskGroupController.java
> +@RequestMapping("task_group")
урлы лучше через дефис прописывать

2023-09-27 07:11 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskGroupController.java
> +    @GetMapping("/addTaskToGroup/{idTask}to{idGroup}")
Id в url лучше не смешивать с текстом, а разделять слэшами. 
Здесь подошел бы такой url: `task-group/{taskGroupId}/add-task/{taskId}`, где первый task-group - берется из requestMapping-а указанного над классом

2023-09-27 07:11 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskGroupController.java
> +    @PostMapping("/save_update")
У тебя два метода с префиксом save в url. Это вносит путаницу. Предлагаю один назвать create, а второй update

2023-09-27 07:11 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskController.java
> +    public TaskController(TaskRepository taskRepository, TaskGroupRepository taskGroupRepository) {
Заведи taskService и TaskGroupService и вынеси всю логику в сервисы. Внутри этих сервисов используй репозитории. А репозитории из контроллеров удали

2023-09-27 07:11 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskGroupController.java
> +    public TaskGroupController(TaskGroupRepository taskGroupRepository, TaskRepository taskRepository) {
Заведи taskService и TaskGroupService и вынеси всю логику в сервисы. Внутри этих сервисов используй репозитории. А репозитории из контроллеров удали

2023-09-27 07:11 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskGroupController.java
> +        TaskGroup taskGroup = taskGroupRepository.findById(id).orElse(null);
Не используй плз orElse(null). Замени на orElseThrow

2023-09-27 07:11 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskGroupController.java
> +        TaskGroup newTaskGroup = taskGroupRepository.findById(idGroup).orElse(null);
Не используй плз orElse(null). Замени на orElseThrow

2023-09-27 07:11 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskController.java
> +        Task task = taskRepository.findById(id).orElse(null);
Не используй плз orElse(null). Замени на orElseThrow

2023-09-27 07:11 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskController.java
> +    @PostMapping("/save_update")
У тебя два метода с префиксом save в url. Это вносит путаницу. Предлагаю один назвать create, а второй update

2023-09-27 07:11 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskGroupController.java
> +        return "task_group/task_group_update";
Не нужно создавать две одинаковые формы для редактирования и создания сущности. Используй одну форму (я про html файл). В одном случае передавай в нее пустой объект (для создания, используя new), а во втором случае передавай в нее объект из репозитория (для редактирования)

2023-09-27 07:11 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskGroupController.java
> +        return "task_group/task_group_update";
Тоже самое касается тасок

2023-09-27 15:03 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/repository/TaskGroupRepository.java
> +    public List<TaskGroup> findAllByOrderByIdAsc();
Нет, при запуске проекта он крашится

2023-09-27 15:03 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/repository/TaskRepository.java
> +    public List<Task> findAllByOrderByIdAsc();
Нет, при запуске проекта он крашится

2023-09-27 15:52 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/entity/TaskGroup.java
> +    private long id;
Сделал

2023-09-27 15:52 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskGroupController.java
> +@RequestMapping("task_group")
Сделал

2023-09-27 15:52 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskGroupController.java
> +    @GetMapping("/addTaskToGroup/{idTask}to{idGroup}")
Сделал

2023-09-27 15:52 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskController.java
> +    @PostMapping("/save_update")
Сделал

2023-09-27 17:02 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskGroupController.java
> +    @PostMapping("/save_update")
сделал

2023-09-27 17:34 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskGroupController.java
> +        return "task_group/task_group_update";
сделал

2023-09-27 17:36 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskController.java
> +        Task task = taskRepository.findById(id).orElse(null);
Сделал

2023-09-27 17:36 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskGroupController.java
> +        TaskGroup newTaskGroup = taskGroupRepository.findById(idGroup).orElse(null);
Сделал

2023-09-27 17:37 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskGroupController.java
> +        TaskGroup taskGroup = taskGroupRepository.findById(id).orElse(null);
Сделал

2023-09-28 05:29 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskController.java
> +    public TaskController(TaskRepository taskRepository, TaskGroupRepository taskGroupRepository) {
Сделал

2023-09-28 05:30 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/controller/TaskGroupController.java
> +    public TaskGroupController(TaskGroupRepository taskGroupRepository, TaskRepository taskRepository) {
Сделал

2023-09-28 13:23 UTC, zor07 requested changes

2023-09-28 13:23 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/service/TaskService.java
> +    public Task getEmptyTask() {
Лайфхак как определить стоит ли заводить отдельный метод под маленький блок логики: 

Если кода становится меньше, то да. В данном случае кода стало больше. Такие методы лучше не создавать. 

Для создания пустого объекта создай в нем конструктор по умолчанию и внутри него инициализируй все как тебе нужно.

Этот метод удалить

2023-09-28 13:23 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/service/TaskGroupService.java
> +    public TaskGroup getEmptyTaskGroup() {
Лайфхак как определить стоит ли заводить отдельный метод под маленький блок логики:

Если кода становится меньше, то да. В данном случае кода стало больше. Такие методы лучше не создавать.

Для создания пустого объекта создай в нем конструктор по умолчанию и внутри него инициализируй все как тебе нужно.

Этот метод удалить

2023-09-28 13:23 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/entity/TaskGroup.java
> +    public long getId() {
Long. 

Если твое поле id будет null то возникнет exception когда jvm попытается привести null к примитиву long

2023-09-28 13:23 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/entity/TaskGroup.java
> +    public void setId(long id) {
Long

2023-09-28 13:23 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/service/TaskGroupService.java
> +        return taskGroupRepository.findById(id).orElseThrow();
Нужно не просто orElseThrow, а бросать свой exception. Заведи пакет exception и добавь в него свое непроверяемое исключение EntityNotFoundException. И внутри orElseThrow бросай его

2023-09-28 13:23 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/service/TaskGroupService.java
> +        TaskGroup newTaskGroup = taskGroupRepository.findById(taskGroupId).orElseThrow();
Нужно не просто orElseThrow, а бросать свой exception. Заведи пакет exception и добавь в него свое непроверяемое исключение EntityNotFoundException. И внутри orElseThrow бросай его

2023-09-28 13:23 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/entity/TaskGroup.java
> +    public void addTask(Task task) {
Не нашел где используется этот метод. Если не используется - удали

2023-09-28 13:23 UTC, zor07 commented on src/main/java/ru/sumarokov/task_tracker/entity/TaskGroup.java
> +    public void removeTask(Task task) {
Не нашел где используется этот метод. Если не используется - удали

2023-09-28 15:13 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/service/TaskGroupService.java
> +    public TaskGroup getEmptyTaskGroup() {
Сделал

2023-09-28 15:13 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/entity/TaskGroup.java
> +    public long getId() {
Сделал

2023-09-28 15:13 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/service/TaskService.java
> +    public Task getEmptyTask() {
Сделал

2023-09-28 15:15 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/entity/TaskGroup.java
> +    public void setId(long id) {
Сделал

2023-09-28 15:27 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/service/TaskGroupService.java
> +        return taskGroupRepository.findById(id).orElseThrow();
Сделал

2023-09-28 15:27 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/service/TaskGroupService.java
> +        TaskGroup newTaskGroup = taskGroupRepository.findById(taskGroupId).orElseThrow();
Сделал

2023-09-28 15:28 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/entity/TaskGroup.java
> +    public void addTask(Task task) {
Сделал

2023-09-28 15:28 UTC, MikhailSumarokov95 commented on src/main/java/ru/sumarokov/task_tracker/entity/TaskGroup.java
> +    public void removeTask(Task task) {
Сделал

2023-09-29 15:05 UTC, merged